/* Patna News Watch — renders data.json generated by generate.py */
(function () {
  "use strict";

  var TYPE_ICONS = {
    news: "📰", facebook: "📘", instagram: "📸",
    youtube: "▶️", x: "𝕏", threads: "🧵"
  };
  var TYPE_LABELS = {
    news: "News site", facebook: "Facebook", instagram: "Instagram",
    youtube: "YouTube", x: "X", threads: "Threads"
  };
  var BADGE_CLASS = {
    verified: "b-verified",
    corroborated: "b-corroborated",
    single: "b-single"
  };
  var MONTHS = ["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"];

  var state = { q: "", topic: "all", badge: "all", data: null };

  function esc(s) {
    return String(s).replace(/[&<>"']/g, function (c) {
      return {"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c];
    });
  }

  function fmtDate(iso) {
    var m = /^(\d{4})-(\d{2})-(\d{2})/.exec(iso || "");
    if (!m) return esc(iso || "");
    return parseInt(m[3], 10) + " " + MONTHS[parseInt(m[2], 10) - 1] + " " + m[1];
  }

  function badgeFor(story) {
    return '<span class="badge ' + BADGE_CLASS[story.genuineness] + '">' +
      esc(story.genuineness_label) + "</span>";
  }

  function typeOf(s) {
    if (TYPE_ICONS[s.type]) return s.type;
    var u = (s.url || "").toLowerCase();
    if (u.indexOf("facebook.com") !== -1 || u.indexOf("fb.watch") !== -1) return "facebook";
    if (u.indexOf("instagram.com") !== -1) return "instagram";
    if (u.indexOf("youtube.com") !== -1 || u.indexOf("youtu.be") !== -1) return "youtube";
    if (u.indexOf("x.com") !== -1 || u.indexOf("twitter.com") !== -1) return "x";
    if (u.indexOf("threads.com") !== -1 || u.indexOf("threads.net") !== -1) return "threads";
    return "news";
  }

  function cardHTML(story) {
    var srcs = story.sources.map(function (s) {
      var t = typeOf(s);
      var icon = TYPE_ICONS[t] || "🔗";
      var label = TYPE_LABELS[t] || t;
      return '<li><span class="src-type" title="' + esc(label) + '">' + icon + "</span>" +
        '<a href="' + esc(s.url) + '" target="_blank" rel="noopener">' +
        esc(s.outlet) + "</a></li>";
    }).join("");

    var topics = (story.topics || []).map(function (t) {
      return '<span class="topic">' + esc(t) + "</span>";
    }).join("");

    return '<article class="card">' +
      '<div class="card-top">' + badgeFor(story) +
      '<span class="card-date">' + fmtDate(story.date) + "</span></div>" +
      "<h2>" + esc(story.headline) + "</h2>" +
      (story.summary ? '<p class="card-summary">' + esc(story.summary) + "</p>" : "") +
      (topics ? '<div class="topics">' + topics + "</div>" : "") +
      '<ul class="sources">' + srcs + "</ul>" +
      '<div class="src-count">' + story.source_count +
      (story.source_count === 1 ? " independent source" : " independent sources") + "</div>" +
      "</article>";
  }

  function matches(story) {
    if (state.badge !== "all" && story.genuineness !== state.badge) return false;
    if (state.topic !== "all" && (story.topics || []).indexOf(state.topic) === -1) return false;
    if (state.q) {
      var hay = (story.headline + " " + (story.summary || "")).toLowerCase();
      if (hay.indexOf(state.q) === -1) return false;
    }
    return true;
  }

  function render() {
    var stories = state.data.stories.filter(matches);
    document.getElementById("stories").innerHTML = stories.map(cardHTML).join("");
    document.getElementById("empty").hidden = stories.length > 0;
  }

  function buildTopicChips(topics) {
    var row = document.getElementById("topic-chips");
    var html = '<button class="chip active" data-topic="all">All topics</button>';
    topics.forEach(function (t) {
      html += '<button class="chip" data-topic="' + esc(t) + '">' +
        esc(t.charAt(0).toUpperCase() + t.slice(1)) + "</button>";
    });
    row.innerHTML = html;
    row.addEventListener("click", function (e) {
      var btn = e.target.closest("[data-topic]");
      if (!btn) return;
      state.topic = btn.getAttribute("data-topic");
      row.querySelectorAll(".chip").forEach(function (c) {
        c.classList.toggle("active", c === btn);
      });
      render();
    });
  }

  function initControls() {
    document.getElementById("search").addEventListener("input", function (e) {
      state.q = e.target.value.trim().toLowerCase();
      render();
    });
    document.getElementById("badge-chips").addEventListener("click", function (e) {
      var btn = e.target.closest("[data-badge]");
      if (!btn) return;
      state.badge = btn.getAttribute("data-badge");
      this.querySelectorAll(".chip").forEach(function (c) {
        c.classList.toggle("active", c === btn);
      });
      render();
    });
  }

  fetch("data.json", { cache: "no-store" })
    .then(function (r) {
      if (!r.ok) throw new Error("HTTP " + r.status);
      return r.json();
    })
    .then(function (data) {
      state.data = data;
      document.getElementById("last-updated").textContent =
        data.generated_at_ist || data.generated_at || "unknown";
      document.getElementById("story-count").textContent =
        data.story_count + (data.story_count === 1 ? " story" : " stories") +
        " (last 7 days)";
      var topics = {};
      data.stories.forEach(function (s) {
        (s.topics || []).forEach(function (t) { topics[t] = true; });
      });
      buildTopicChips(Object.keys(topics).sort());
      initControls();
      render();
    })
    .catch(function (err) {
      document.getElementById("stories").innerHTML =
        '<p class="empty">Could not load news data. (' + esc(err.message) + ")</p>";
    });
})();
