/* Patna Pulse — renders data.json generated by generate.py
   Dark news-channel theme: hero top story, image cards, click-to-play video. */
(function () {
  "use strict";

  var TYPE_ICONS = {
    news: "📰", facebook: "📘", instagram: "📸",
    youtube: "▶️", x: "𝕏", threads: "🧵"
  };
  var TYPE_LABELS = {
    news: "News site", facebook: "Facebook", instagram: "Instagram",
    youtube: "YouTube", x: "X", threads: "Threads"
  };
  var BADGE_CLASS = {
    verified: "b-verified",
    corroborated: "b-corroborated",
    single: "b-single"
  };
  var MONTHS = ["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"];

  var state = { q: "", topic: "all", badge: "all", data: null };

  function esc(s) {
    return String(s).replace(/[&<>"']/g, function (c) {
      return {"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c];
    });
  }

  function fmtDate(iso) {
    var m = /^(\d{4})-(\d{2})-(\d{2})/.exec(iso || "");
    if (!m) return esc(iso || "");
    return parseInt(m[3], 10) + " " + MONTHS[parseInt(m[2], 10) - 1] + " " + m[1];
  }

  function relDate(iso) {
    var m = /^(\d{4})-(\d{2})-(\d{2})/.exec(iso || "");
    if (!m) return "";
    var d = new Date(parseInt(m[1],10), parseInt(m[2],10) - 1, parseInt(m[3],10));
    var now = new Date();
    var days = Math.floor((now - d) / 86400000);
    if (days <= 0) return "Today";
    if (days === 1) return "Yesterday";
    return days + " days ago";
  }

  function badgeFor(story) {
    return '<span class="badge ' + BADGE_CLASS[story.genuineness] + '">' +
      esc(story.genuineness_label) + "</span>";
  }

  function typeOf(s) {
    if (TYPE_ICONS[s.type]) return s.type;
    var u = (s.url || "").toLowerCase();
    if (u.indexOf("facebook.com") !== -1 || u.indexOf("fb.watch") !== -1) return "facebook";
    if (u.indexOf("instagram.com") !== -1) return "instagram";
    if (u.indexOf("youtube.com") !== -1 || u.indexOf("youtu.be") !== -1) return "youtube";
    if (u.indexOf("x.com") !== -1 || u.indexOf("twitter.com") !== -1) return "x";
    if (u.indexOf("threads.com") !== -1 || u.indexOf("threads.net") !== -1) return "threads";
    return "news";
  }

  function sourcesHTML(story) {
    var srcs = story.sources.map(function (s) {
      var t = typeOf(s);
      var icon = TYPE_ICONS[t] || "🔗";
      return '<a class="src-btn" href="' + esc(s.url) + '" target="_blank" rel="noopener">' +
        '<span title="' + esc(TYPE_LABELS[t] || t) + '">' + icon + "</span>" +
        esc(s.outlet) + "</a>";
    }).join("");
    return '<div class="sources">' + srcs +
      '<span class="src-count">' + story.source_count +
      (story.source_count === 1 ? " independent source" : " independent sources") +
      "</span></div>";
  }

  function topicsHTML(story) {
    var topics = (story.topics || []).map(function (t) {
      return '<span class="topic">' + esc(t) + "</span>";
    }).join("");
    return topics ? '<div class="topics">' + topics + "</div>" : "";
  }

  function mediaHTML(story, hero) {
    var cls = hero ? "hero-media" : "card-media";
    var fbCls = hero ? "hero-fallback" : "media-fallback";
    var inner = story.image
      ? '<img src="' + esc(story.image) + '" alt="" loading="lazy">'
      : '<div class="' + fbCls + '">📡</div>';
    if (story.video_embed) {
      inner += '<button class="play-btn" data-video="' + esc(story.video_embed) +
        '" aria-label="Play video">▶</button>';
    }
    return '<div class="' + cls + '" data-fb="' + fbCls + '">' + inner + "</div>";
  }

  function heroHTML(story) {
    return '<article class="hero-card">' +
      mediaHTML(story, true) +
      '<div class="hero-shade"></div>' +
      '<div class="hero-body">' +
      '<span class="hero-kicker">🔥 TOP STORY</span>' +
      "<h2>" + esc(story.headline) + "</h2>" +
      (story.summary ? '<p class="lede">' + esc(story.summary) + "</p>" : "") +
      '<div class="hero-cta">' + badgeFor(story) +
      (story.video_embed
        ? '<button class="btn btn-primary" data-video="' + esc(story.video_embed) + '">▶ Watch video</button>'
        : "") +
      (story.sources[0]
        ? '<a class="btn btn-ghost" href="' + esc(story.sources[0].url) + '" target="_blank" rel="noopener">Read full story ↗</a>'
        : "") +
      "</div></div></article>";
  }

  function cardHTML(story) {
    return '<article class="card">' +
      mediaHTML(story, false) +
      '<div class="card-body">' +
      '<div class="card-meta"><span class="rel">' + esc(relDate(story.date)) + "</span>" +
      "<span>" + fmtDate(story.date) + "</span></div>" +
      "<h3>" + esc(story.headline) + "</h3>" +
      (story.summary ? '<p class="card-summary">' + esc(story.summary) + "</p>" : "") +
      topicsHTML(story) +
      sourcesHTML(story) +
      "</div></article>";
  }

  function matches(story) {
    if (state.badge !== "all" && story.genuineness !== state.badge) return false;
    if (state.topic !== "all" && (story.topics || []).indexOf(state.topic) === -1) return false;
    if (state.q) {
      var hay = (story.headline + " " + (story.summary || "")).toLowerCase();
      if (hay.indexOf(state.q) === -1) return false;
    }
    return true;
  }

  function render() {
    var stories = state.data.stories.filter(matches);
    // hero = newest story carrying a picture or video (falls back to newest)
    var hero = stories.filter(function (s) { return s.image || s.video_embed; })[0]
      || stories[0];
    var rest = stories.filter(function (s) { return s !== hero; });
    document.getElementById("hero").innerHTML = hero ? heroHTML(hero) : "";
    document.getElementById("grid").innerHTML = rest.map(cardHTML).join("");
    document.getElementById("empty").hidden = stories.length > 0;
  }

  function buildTicker(stories) {
    var items = stories.slice(0, 8).map(function (s) {
      return '<span><span class="tdot">●</span> <b>' + esc(s.headline) + "</b></span>";
    }).join("");
    document.getElementById("ticker-track").innerHTML = items + items; // loop seam
  }

  function buildTopicChips(topics) {
    var row = document.getElementById("topic-chips");
    var html = '<button class="chip active" data-topic="all">All topics</button>';
    topics.forEach(function (t) {
      html += '<button class="chip" data-topic="' + esc(t) + '">' +
        esc(t.charAt(0).toUpperCase() + t.slice(1)) + "</button>";
    });
    row.innerHTML = html;
    row.addEventListener("click", function (e) {
      var btn = e.target.closest("[data-topic]");
      if (!btn) return;
      state.topic = btn.getAttribute("data-topic");
      row.querySelectorAll(".chip").forEach(function (c) {
        c.classList.toggle("active", c === btn);
      });
      render();
    });
  }

  function initControls() {
    document.getElementById("search").addEventListener("input", function (e) {
      state.q = e.target.value.trim().toLowerCase();
      render();
    });
    document.getElementById("badge-chips").addEventListener("click", function (e) {
      var btn = e.target.closest("[data-badge]");
      if (!btn) return;
      state.badge = btn.getAttribute("data-badge");
      this.querySelectorAll(".chip").forEach(function (c) {
        c.classList.toggle("active", c === btn);
      });
      render();
    });
    // click-to-play video (delegated: works for hero + cards)
    document.addEventListener("click", function (e) {
      var btn = e.target.closest("[data-video]");
      if (!btn) return;
      var url = btn.getAttribute("data-video") + "?autoplay=1&rel=0";
      var frame = document.createElement("div");
      frame.className = btn.closest("#hero") ? "hero-video" : "card-video";
      frame.innerHTML = '<iframe src="' + esc(url) + '" title="Story video" ' +
        'allow="accelerometer; autoplay; encrypted-media; picture-in-picture" ' +
        'allowfullscreen></iframe>';
      var media = btn.closest(".hero-media, .card-media");
      media.appendChild(frame);
      media.querySelectorAll(".play-btn").forEach(function (b) { b.remove(); });
    });
    // graceful image fallback: if a story image fails to load, swap in the styled tile
    document.addEventListener("error", function (e) {
      var t = e.target;
      if (t && t.tagName === "IMG") {
        var media = t.closest(".hero-media, .card-media");
        if (media && !media.querySelector(".hero-fallback, .media-fallback")) {
          var fb = document.createElement("div");
          fb.className = media.getAttribute("data-fb");
          fb.textContent = "📡";
          media.insertBefore(fb, media.firstChild);
          t.remove();
        }
      }
    }, true);
  }

  fetch("data.json", { cache: "no-store" })
    .then(function (r) {
      if (!r.ok) throw new Error("HTTP " + r.status);
      return r.json();
    })
    .then(function (data) {
      state.data = data;
      document.getElementById("last-updated").textContent =
        data.generated_at_ist || data.generated_at || "unknown";
      document.getElementById("story-count").textContent =
        data.story_count + (data.story_count === 1 ? " story" : " stories");
      var topics = {};
      data.stories.forEach(function (s) {
        (s.topics || []).forEach(function (t) { topics[t] = true; });
      });
      buildTicker(data.stories);
      buildTopicChips(Object.keys(topics).sort());
      initControls();
      render();
    })
    .catch(function (err) {
      document.getElementById("grid").innerHTML =
        '<p class="empty">Could not load news data. (' + esc(err.message) + ")</p>";
    });
})();
